#下面这些内容是为了让MyBatis映射
#指定Mybatis的Mapper文件
mybatis:
  mapper-locations: classpath:mappers/*xml
  #指定Mybatis的实体目录
  type-aliases-package: com.example.DepotManage.entity
  #打印日志
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.example.DepotManage.entity
  mapper-locations: classpath:mappers/*xml

# 应用服务 WEB 访问端口
server:
  port: 9090

# 应用名称
spring:
  application:
    name: DepotManage
  # 数据库驱动：
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据源名称
    name: defaultDataSource
    # 数据库连接地址
    url: jdbc:mysql://localhost:3306/depot_manage?serverTimezone=UTC&characterEncoding=utf8
    # 数据库用户名&密码：
    username: root
    password: root
  # 配置本地资源路径
  web:
    resources:
      static-locations: /META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
